USE [master]
GO
/****** Object:  Database [IOBDB]    Script Date: 27/04/2023 07:41:13 ******/
CREATE DATABASE [IOBDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'IOBDB', FILENAME = N'/var/opt/mssql/data/IOBDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'IOBDB_log', FILENAME = N'/var/opt/mssql/data/IOBDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [IOBDB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [IOBDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [IOBDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [IOBDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [IOBDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [IOBDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [IOBDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [IOBDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [IOBDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [IOBDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [IOBDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [IOBDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [IOBDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [IOBDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [IOBDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [IOBDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [IOBDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [IOBDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [IOBDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [IOBDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [IOBDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [IOBDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [IOBDB] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [IOBDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [IOBDB] SET RECOVERY FULL 
GO
ALTER DATABASE [IOBDB] SET  MULTI_USER 
GO
ALTER DATABASE [IOBDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [IOBDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [IOBDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [IOBDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [IOBDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [IOBDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'IOBDB', N'ON'
GO
ALTER DATABASE [IOBDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [IOBDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [IOBDB]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 27/04/2023 07:41:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Compromissos]    Script Date: 27/04/2023 07:41:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Compromissos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Titulo] [nvarchar](max) NOT NULL,
	[Descricao] [nvarchar](max) NOT NULL,
	[DataCompromisso] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_Compromissos] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ContatoCompromisso]    Script Date: 27/04/2023 07:41:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ContatoCompromisso](
	[CompromissosId] [int] NOT NULL,
	[ContatosId] [int] NOT NULL,
 CONSTRAINT [PK_ContatoCompromisso] PRIMARY KEY CLUSTERED 
(
	[CompromissosId] ASC,
	[ContatosId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Contatos]    Script Date: 27/04/2023 07:41:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Contatos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [nvarchar](max) NOT NULL,
	[Telefone] [nvarchar](max) NULL,
	[Celular] [nvarchar](max) NOT NULL,
	[Email] [nvarchar](max) NOT NULL,
	[DataNascimento] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_Contatos] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Enderecos]    Script Date: 27/04/2023 07:41:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Enderecos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Cep] [nvarchar](max) NOT NULL,
	[Logradouro] [nvarchar](max) NOT NULL,
	[Numero] [nvarchar](max) NULL,
	[Complemento] [nvarchar](max) NULL,
	[Bairro] [nvarchar](max) NULL,
	[Cidade] [nvarchar](max) NOT NULL,
	[Estado] [nvarchar](max) NOT NULL,
	[ContatoId] [int] NOT NULL,
 CONSTRAINT [PK_Enderecos] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Index [IX_ContatoCompromisso_ContatosId]    Script Date: 27/04/2023 07:41:13 ******/
CREATE NONCLUSTERED INDEX [IX_ContatoCompromisso_ContatosId] ON [dbo].[ContatoCompromisso]
(
	[ContatosId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Enderecos_ContatoId]    Script Date: 27/04/2023 07:41:13 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_Enderecos_ContatoId] ON [dbo].[Enderecos]
(
	[ContatoId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ContatoCompromisso]  WITH CHECK ADD  CONSTRAINT [FK_ContatoCompromisso_Compromissos_CompromissosId] FOREIGN KEY([CompromissosId])
REFERENCES [dbo].[Compromissos] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ContatoCompromisso] CHECK CONSTRAINT [FK_ContatoCompromisso_Compromissos_CompromissosId]
GO
ALTER TABLE [dbo].[ContatoCompromisso]  WITH CHECK ADD  CONSTRAINT [FK_ContatoCompromisso_Contatos_ContatosId] FOREIGN KEY([ContatosId])
REFERENCES [dbo].[Contatos] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ContatoCompromisso] CHECK CONSTRAINT [FK_ContatoCompromisso_Contatos_ContatosId]
GO
ALTER TABLE [dbo].[Enderecos]  WITH CHECK ADD  CONSTRAINT [FK_Enderecos_Contatos_ContatoId] FOREIGN KEY([ContatoId])
REFERENCES [dbo].[Contatos] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Enderecos] CHECK CONSTRAINT [FK_Enderecos_Contatos_ContatoId]
GO
USE [master]
GO
ALTER DATABASE [IOBDB] SET  READ_WRITE 
GO
